### ISSUE TITLE
Fails with perls < 5.14

### ISSUE THREAD

**Issue by andk** [athreef/WebService-NextEpisode#1]
As per subject. Diagnostics:

Bareword found where operator expected at /tmp/loop_over_bdir-2958-vi5LbH/WebService-NextEpisode-0.001-0/blib/lib/WebService/NextEpisode.pm line 39, near "s/ /+/gr"

Sample fail report:

http://www.cpantesters.org/cpan/report/c2809a18-942d-11e7-933a-881d62460493

If you want to keep it that way, it would be cool if you could declare your requirement. That way the FAILS are converted to UNKNOWNS. Details about how to do it are on this page: http://wiki.cpantesters.org/wiki/CPANAuthorNotes

HTH&&Thanks,

**Comment by a3f** [comment]
Thanks!
